### ISSUE TITLE
H

### ISSUE THREAD

**Issue by Decapitater** [V0r-T3x/keymaps#1]
H

**Comment by V0r-T3x** [comment]
I'm far to be an expert, but I'm always willing to help.

**Comment by V0r-T3x** [comment]
Yeah if you want, give me your t.me link if you want chat on telegram.

**Comment by Decapitater** [comment]
alright

**Comment by Decapitater** [comment]
https://t.me/Decaptiator

**Comment by Decapitater** [comment]
Back in the game

**Comment by Decapitater** [comment]
Let's go @Decaptator

**Comment by Decapitater** [comment]
Telegram
